title: Taste of Lux
description: Recettes de chefs luxembourgeois
url: "https://paperjam-redaction.github.io"
baseurl: "/tasteoflux"

plugins:
  - jekyll-seo-tag

collections:
  recipes:
    output: true
    permalink: /recettes/:name/

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
